//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chatting
    {
        public int ChattingID { get; set; }
        public int SeatID { get; set; }
        public System.DateTime SendTIme { get; set; }
        public string Text { get; set; }
        public bool Checked { get; set; }
        public bool Sent { get; set; }
    
        public virtual Seat Seat { get; set; }
    }
}
