
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PC_Project.Data
{

using System;
    using System.Collections.Generic;
    
public partial class GameUsingList
{

    public int GameID { get; set; }

    public int CustomerID { get; set; }

    public Nullable<int> UsedTime { get; set; }

    public System.DateTime StartTime { get; set; }



    public virtual Customer Customer { get; set; }

    public virtual Game Game { get; set; }

}

}
