//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int CodeID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public byte[] Photo { get; set; }
        public bool In_stock { get; set; }
    
        public virtual Code Code { get; set; }
    }
}
